spring:
  h2:
    console:
      enabled: true
      path: /test_db
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:./h2/test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: 1234
  thymeleaf:
    enabled: true
    encoding: UTF-8
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
      restart: false
      